<div class="jumbotron">
    <h1>Test App</h1>

    <p>
        Done by Aleksei Kochetkov
    </p>

</div>

<div class="row">

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title"></h2>
            </div>
            <div class="card-body">
                <p>

                </p>

                <p><a class="btn btn-success pull-right" href="" target=""></a>
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title"></h2>
            </div>
            <div class="card-body">
                <p>

                </p>

                <p><a class="btn btn-success pull-right" href="" target=""></a>
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title"></h2>
            </div>
            <div class="card-body">
                <p>

                </p>

                <p><a class="btn btn-success pull-right" href="" target=""></a>
                </p>
            </div>
        </div>
    </div>
</div>
